server:
  port: 82

spring:
  datasource:
    druid:
      default:
        url: jdbc:oracle:thin:@192.168.7.154:1521:tgtstdb
        username: csmbtst
        password: csmbtst
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    #注意如果redis无密码,password可以设置为none
    password: 123456

cross:
   domain: http://localhost:8080,https://localhost:8443,*

wx:
  corpId: test
  appSecret: test

tt:
  deadline: 2019-01-21 20:00:00
  
path:
  log: /usr/local/apps/csm-api-test/logs
  
store:
  db:
    cs:
      userName: test
      password: test
    jd:
      userName: test
      password: test
    zyppdb:
      userName: test
      password: test
      sid: test
      host: localhost
      port: 1521
    rmsdg:
      userName: test
      password: test
      sid: test
      host: localhost
      port: 1521
    