server:
  port: 8181

spring:
  datasource:
    druid:
      default:
        url: jdbc:oracle:thin:@127.0.0.1:1521:CSMOBILE
        username: csmb
        password: csmb
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    #注意如果redis无密码,password可以设置为none
    password: 87032056

cross:
  domain: http://localhost:8080,https://localhost:8443,*

wx:
  corpId: wxb7d37997b7462f8c
  appSecret: 3UPZCw2s81FQfriTV5tAnKAv55tEJJI0Z2-L9eMkucU
  agentId: 1000035
  otherLogo: D:/p2.png
  warnLogo: D:/p2.png
  businessLogo: D:/p2.png
  message:
    whiteIp: 10.12.27.53
     
tt:
  deadline: 2019-01-30 18:00:00
  
path:
  log: D:/csmobile/log

store:
  db:
    cs:
      userName: bbgcs
      password: drowssap
    jd:
      userName: bbgdq
      password: drowssap
    zyppdb:
      userName: BIQUERY
      password: BIQUERY123~
      sid: zyppdb
      host: 192.168.1.28
      port: 1521
    rmsdg:
      userName: rmsquery
      password: rmsquery
      sid: rmsdb
      host: rtkdg-scan.bbgretek.com.cn
      port: 1521